version: '3.1'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_restaurant
    restart: always
    ports:
      - 3309:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: restaurant
      MYSQL_USER: restaurant-api
      MYSQL_PASSWORD: mysql@restaurant
      MYSQL_DATABASE: restaurant
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_general_ci
